name: prophile29
channels:
  - defaults
  - conda-forge
  - bioconda
  - schrodinger
dependencies:
  - python=3.8.5
  - biopython=1.78
  - matplotlib=3.3.2
  - numpy=1.19.2
  - pandas=1.1.3
  - seaborn=0.11.0
  - ipykernel=5.3.4
  - muscle=3.8.1551
  - catboost=0.24.3
  - hmmer=3.3.1
  - pymol=2.4.1
  - tqdm=4.54.0
